spring:
  # DataSource
  datasource:
    url: jdbc:mysql://localhost:3306/db06_sym?serverTimezone=Asia/Taipei
    username: root
    password: password
  # SessionFactory
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  # ViewResolver
  mvc:
    view:
      prefix: /
      suffix: .jsp

server:
  servlet:
    context-path: /TGA104_SYM_Group6